### ISSUE TITLE
Splat conflicts with System.Drawing.Primitives package from Microsoft

### ISSUE THREAD

**Issue by kekekeks** [reactiveui/splat#152]
It's now impossible to use both Splat and packages that are using types from microsoft package.

**Comment by kentcb** [comment]
Haven't tried it, but I'm guessing assigning an assembly alias would disambiguate? Come to think of it, I've _never_ tried assembly aliases with references from NuGets, so interested to hear if this works.

**Comment by mattrichnz** [comment]
This breaks badly with 2.0. On Xamarin.iOS, I'm seeing errors like:
`Method 'System.Drawing.Size.Equals' not found.`

Assembly aliases might work, but may not be practical for existing usage.

**Comment by ghuntley** [comment]
Could you please put together a quick test project and share the GitHub link here. Thanks

**Comment by mattrichnz** [comment]
@ghuntley I have just put together a quick test project. 
Create a new Xamarin.Forms iOS solution and use the following sample code.
You will see a simple equality check produces the issue.

```
namespace SplatPrimitivesBug
{
    using System.Drawing;
    using Splat;

    public partial class SplatPrimitivesBugPage : Xamarin.Forms.ContentPage
    {
        public SplatPrimitivesBugPage()
        {
            InitializeComponent();
            DemonstrateBug();
        }

        /// <summary>
        /// Demonstrates the bug reported here https://github.com/paulcbetts/splat/issues/152.
        /// </summary>
        private void DemonstrateBug()
        {
            var sizeA = new Size(50, 50);
            var sizeB = new Size(100, 100);

            // This will fail with runtime error "Method 'System.Drawing.Size.Equals' not found".
            var failingEqualityCheck = sizeA.Equals(sizeB);
        }
    }
}
```

**Comment by mattrichnz** [comment]
Just wondering if there is any update on this issue?

**Comment by pellea** [comment]
I have the same issue in a .NETStandard 2.0 class library.

> CS0433	The type 'Color' exists in both 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

or 

> CS0433	The type 'Point' exists in both 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

Steps:
1) Create a new .NET Standard 2.0 class library
2) Add Splat 2.0
3) Add a property in a class `public static Point InitialPoint => new Point(13, 12);`

**Comment by SuperJMN** [comment]
I'm having a problem with Splat 2.0: 

Definitely, it's referencing the System.Drawing assembly, so it's unusable in Xamarin Android (and iOS)

This is the output.

5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error : File name: 'System.Drawing.dll'
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1391,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)
========== Build

**Comment by ghuntley** [comment]
This is definitely something that will need to be and I want to see fixed. Please research, discuss on this thread and open a pull request when you have enough direction.

**Comment by paulanthonymorris** [comment]
This is blocking us from updating. I have looked into assembly aliases but am still not sure how to implement. If I can figure it out I will try to address it and put up a PR but don't have a clear plan of attack yet. If anyone can point me to some docs, etc. I would appreciate it.

**Comment by paulcbetts** [comment]
You can probably just nuke the Splat types now that there's a substitute package, that was the whole point of this shim anyways :)

**Comment by paulanthonymorris** [comment]
@ghuntley or @paulcbetts: Should I put up the PR that deletes the Splat types against develop or master?

**Comment by ghuntley** [comment]
@paulanthonymorris develop.

**Comment by paulanthonymorris** [comment]
@paulcbetts Please check me here. Is the goal to blow away the shim types from source? Or do we just want to remove the compile directives for these shim types from the netstandard csproj?

**Comment by pellea** [comment]
Will this modification/commit packaged in a prerelease version of Splat? 

ReactiveUI 8.0 is still "unusable" because of this issue.

**Comment by ghuntley** [comment]
@pellea can you raise an issue on `reactiveui/reactiveui` explaining the problems you are facing with ReactiveUI v8?

**Comment by pellea** [comment]
In my code I use System.Drawing class alongside with ReactiveObject class. When I upgraded my working project to reactiveui 7.4 to reactiveui 8.0, it stops working because the reactiveui 8.0 required Splat 2.0. 

I don't have any issue anymore. I replaced the System.Drawing.* classes I was using by string or other "compatible types".

**Comment by MKuckert** [comment]
Can I help in any way? Is there an outstanding PR from @paulanthonymorris removing the classes altogether or what would be a desired solution?

**Comment by paulanthonymorris** [comment]
@olevett said he took my pr and folded it in to his work so he has the baton now. Let me know if more is needed from me. Thank you.

**Comment by olevett** [comment]
@MKuckert as @paulanthonymorris says, this got rolled in to #159, which is being worked on slowly...if you're up for piling in on that that would be the most help right now.

At the moment, it's not building correctly on AppVeyor, but not entirely clear why.

**Comment by MKuckert** [comment]
I see you've added a load of changes lately. Is there a real remainder for me?

**Comment by pellea** [comment]
Is there any known temporary fix or preview package we can use? 

We still can't use the `Point` class when using Spat 2.0.0 in the project.

**Comment by ElteHupkes** [comment]
Since there is no explicit mention of it in this issue yet: there's a version 7.0 out which removes the Splat dependency. I'm using it successfully in my .NET Standard 2.0 project.

**Comment by EmilAlipiev** [comment]
Is there any solution for this?

**Comment by cabauman** [comment]
Hopefully that PR will get wrapped up soon but until then...

It's not a pretty solution, but here it is.
Like @kentcb hinted at earlier in this thread, you can use an assembly alias to disambiguate. It's not possible via the property window but I found this workaround: https://github.com/NuGet/Home/issues/4989#issuecomment-310565840

Just add the following to the netstandard .csproj:

```
<Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Splat'">
        <Aliases>SplatAlias</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

But of course by doing this, you have to modify all your Splat references.

extern alias SplatAlias

using SplatAlias::Splat

**Comment by kzu** [comment]
I used @cabauman trick to upgrade Microsoft' [Smart360](https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps) demo app to netstandard2.0 :)

**Comment by ghuntley** [comment]
Resolved in #159

**Comment by alexshikov** [comment]
After update from Splat 2.0.0 to 3.0.0 I have a hundred errors like this:
```
error CS1929: 'Color' does not contain a definition for 'ToNative' and the best extension method overload 'BitmapMixins.ToNative(IBitmap)' requires a receiver of type 'IBitmap'
```

When I try to fix that by adding `System.Drawing.Primitives` there is an error about `Color` defined in both libraries `System.Drawing.Primitives` and `OpenTk-1.0` =|

**Comment by ghuntley** [comment]
Alex can you please open a new issue and attach a minimal repro? Ta.

**Comment by takacsalbert** [comment]
Hi @ghuntley,

I experience the same as @alexshikov. Color.ToNative(), FromNative(), and IBitmap.ToNative(), FromNative() are missing. I tried UWP 16299 and Xamarin.Android with .NET Standard 2.0
Quick and dirty solution for me: implemented these for myself based on removed code from the library. For UWP it seems to be that removing the old WinRT code was a bad idea. I haven't touched Android yet, but for the first run it is the same.
Splat 2.0.0 was ok, but that's not compatible with .NET Standard 2.0 because of the System.Drawing.Primitives issue.

Repro Steps:
Create a UWP project with minimum and target version 16299
Reference latest Splat (atm 5.0.1) from nuget
Try to use System.Drawing.Color.ToNative()

Can you please fix this?

**Comment by glennawatson** [comment]
I pushed through to NuGet 5.0.2 just now with Colt's PR in it.

**Comment by takacsalbert** [comment]
@glennawatson @cabauman 
Thank you guys, updating to 5.0.2 solves the issues. Awesome quickness. ;)
